spring:
  application:
    name: FakeCommerce
  datasource:
    url: ${path}
    username: ${username}
    password: ${sqlpasscode}
    driver-class-name: ${driver_class_name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migrations

server:
  port: ${port:8081}
